apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
      - name: item-service
        image: rutujanemane028/item_service:latest  # Ensure this image exists on Docker Hub
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /items  # Assuming /items is a valid path for your service
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /items
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
